#!/bin/bash

keymap=${2:-justincmoy}

build_keyboard() {
    pushd "$(dirname "$0")"/.. > /dev/null
        docker run --rm \
            -v $(pwd):/keyboard-layouts \
            -u $(id -u):$(id -g) \
            -e LOCAL_KEYBOARD_PATH="${1}" \
            -e KEYBOARD="${1}" \
            -e KEYMAP="${keymap}" \
            "${BUILDER_IMAGE_NAME}" \
            /keyboard-layouts/scripts/link-and-build-keyboard

    popd > /dev/null
}

build_keyboard $@
