#!/bin/bash -x

cd "${QMK_HOME}/buttery_engine"
python my_parser.py "/keyboard-layouts/qmk/keymap_def.yaml"

mkdir -p "${QMK_HOME}"/keyboards/${KEYBOARD}/keymaps/${KEYMAP}
cp /keyboard-layouts/qmk/"${LOCAL_KEYBOARD_PATH}"/* "${QMK_HOME}"/keyboards/${KEYBOARD}/keymaps/"${KEYMAP}"
cp /keyboard-layouts/qmk/common/config.h "${QMK_HOME}"/keyboards/${KEYBOARD}/keymaps/"${KEYMAP}"
cp "$QMK_HOME/buttery_engine/keymap.c" "${QMK_HOME}"/keyboards/${KEYBOARD}/keymaps/${KEYMAP}

cd "${QMK_HOME}"
qmk compile -kb "${KEYBOARD}" -km "${KEYMAP}"

cp .build/*.hex /keyboard-layouts/
